### ISSUE TITLE
[1.12.2] Instant-Crash upon launch if Dynamic Surroundings is installed.

### ISSUE THREAD

**Issue by SonicX8000** [bl4ckscor3/ParticleCulling#1]
Minecraft: 1.12.2
Forge: 14.23.5.2854

Mods: 4
DynamicSurroundings-1.12.2-3.6.0.2
jei_1.12.2-4.15.0.291
OreLib-1.12.2-3.6.0.1
particleculling-1.12.2-v1.0.1

-----

The game crashes upon launching if Dynamic Surroundings is installed with Particle Culling. No crash report is given when this occurs.

**Comment by bl4ckscor3** [comment]
Update Dynamic Surroundings. The author fixed incompatibility with certain mods in version [1.12.2-3.6.1.0](https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings/files/2922489).

If you still cannot get it to work, try installing [this mod](https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility).

**Comment by SonicX8000** [comment]
Oops... should've checked if there was an update for Dynamic Surroundings before opening up the issue. The crash no longer occurs after updating it.
