### ISSUE TITLE
[Issue] Thaumcraft 6 Effects focus effects don't render

### ISSUE THREAD

**Issue by Vapaman** [bl4ckscor3/ParticleCulling#3]
Modlist:

![kuva](https://user-images.githubusercontent.com/77460466/122623123-99972c00-d0a3-11eb-9af3-3a5cd9fddfbd.png)

When particle culling is disabled Thaumcrafts focus bolts render normally.

What normally it should look like:
![2021-06-19_02 11 30](https://user-images.githubusercontent.com/77460466/122623319-45d91280-d0a4-11eb-89a2-930937d198dc.png)

**Comment by bl4ckscor3** [comment]
The particle's bounding box that Particle Culling uses to determine if a particle should be culled or not is very likely set incorrectly by Thaumcraft. 
I also no longer update my mods for 1.12.2.

**Comment by xJon** [comment]
If you can consider it, resolving this issue would be really appreciated!

**Comment by bl4ckscor3** [comment]
Resolution available in v1.4.3
