### ISSUE TITLE
[FALSE POSITIVE] Possible malware in mod

### ISSUE THREAD

**Issue by Bobertjr85** [bl4ckscor3/ParticleCulling#4]
I recently got a windows defender notification of a trojan named "Uwamson.A!ml" located in "particleculling-1.12.2-v1.2.jar". Others playing the same modpack have reported the same notification from windows defender. Allowing defender to remove it does not cause any negative effects.

**Comment by bl4ckscor3** [comment]
This is a false positive. The code is open source and available on this repository, you or someone else you trust and knows code can check for themselves. Same goes for decompiling the jar file. Feel free to do so to verify that my code does not contain any malware. Windows Defender might be tripping over the [mixin library](https://github.com/SpongePowered/Mixin) that I use to modify Minecraft's code, however it is a completely safe library to use.
