### ISSUE TITLE
Mod Combo Crash on flight take off

### ISSUE THREAD

**Issue by Keaft** [bl4ckscor3/ParticleCulling#6]
Log: 
[crash-2022-03-28_13.17.49-server.txt](https://github.com/bl4ckscor3/ParticleCulling/files/8365702/crash-2022-03-28_13.17.49-server.txt)

Minecraft 1.12.2, Forge 14.23.5.2859

I've whittled it down to this list of 19 mods. Remove any one and the crash goes away. ParticleCulling just so happens to be the last one added to my pack.
![image](https://user-images.githubusercontent.com/68153/160471759-32c6c504-ff26-41cf-b135-b937af4ae351.png)
(Note that mixins is being handled by either Sledgehammer, Randompatches, or FoamFix I can't remember which.)

Equip a normal vanilla Elytra on your back, and a Magic Feather in the bauble slot.
![image](https://user-images.githubusercontent.com/68153/160472149-035c49e0-5be5-4d9e-9730-9649ae96e7b2.png)

While standing on the ground use a firework to **take off**. Creative mode is fine and makes it so you can survive. The important part seems to be only on take off and only randomly, so spamming it quickly by taking off and landing makes it crash the quickest.

It would appear that something about either the player entity or firework entity is running a foul with the normal vanilla functions. The best guess I have is that between all the patching there is a null value being passed along crashing the game. 

Anywho! I noticed that you have an ignore list for particles. I wonder if I should start by ignoring the firework particles? Would you happen to know what to add to that list to ignore the proper particle?

**Comment by bl4ckscor3** [comment]
Yeah, this is not caused by Particle Culling, as Minecraft's entity tracker is throwing the error, and this mod does not touch that.
Adding `net.minecraft.client.particle.ParticleFirework` will ignore the firework particle.

**Comment by Keaft** [comment]
Hey thanks for the clarification! Sure enough even removing ParticleCulling it still crashes.
