### ISSUE TITLE
Friendly Thaumcraft Pech + Particle Culling = Crash?

### ISSUE THREAD

**Issue by Handeril** [bl4ckscor3/ParticleCulling#7]
A gremlin in it's own right.

In my in-development modpack, I discovered that using Particle Culling and being near a Friendly Thaumcraft Pech is almost-guaranteed to crash the game for some reason. An easy way to make the Peches (Pechs?) friendly is by throwing tons of gold at them.

I got lucky in guessing that this mod was possibly the issue, as it's one of the "recent" mods added.

Logs:

[crash-2022-07-29_18.22.40-server.txt](https://github.com/bl4ckscor3/ParticleCulling/files/9224136/crash-2022-07-29_18.22.40-server.txt)
[2022-07-29-2.log](https://github.com/bl4ckscor3/ParticleCulling/files/9224138/2022-07-29-2.log)

**Comment by bl4ckscor3** [comment]
I'm afraid to say, that Particle Culling is not the cause of this. It's a client side mod, and this is a server side crash. Additionally, this crash occured while updating an entity, and Particle Culling does nothing with entities. This type of crash (`ConcurrentModificationException`) would also not appear, as Particle Culling does nothing that could cause this.
